((haskell-mode . ((haskell-indent-spaces . 2)
                  (haskell-process-use-ghci . t)
                  (lsp-haskell-server-path . "ghcide")))
 (hamlet-mode . ((hamlet/basic-offset . 4)
                 (haskell-process-use-ghci . t))))
