import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

df = pd.read_csv("/home/joseph/Projects/open-strings/survey/survey_responses.csv")
df = df[df.user != "Joseph Morag"]
df.piece = df.piece.str.split(",").str[0]
df["Generated by"] = df["piece"].replace(["Prokofiev", "Ysaÿe", "Bartók"], "Machine")
df["Generated by"] = df["Generated by"].replace(["Bruch", "Mozart", "Strauss"], "Human")

save_path = "/home/joseph/NYU/Spring-2021/Thesis 2/thesis/figures/"

def plot_metric_swarm(metric, labels, type="swarm"):
    fig, ax = plt.subplots(figsize=(10, 5))
    if type == "swarm":
        sns.swarmplot(
            x="piece",
            y=metric,
            hue="Generated by",
            data=df,
            ax=ax,
            size=7,
        )
    elif type == "boxen":
        sns.boxenplot(x=metric, y="piece", hue="Generated by", data=df, ax=ax)
    ax.set_yticks(np.arange(5))
    ax.set_yticklabels(labels)
    ax.grid(axis="x")

    ax.set_xlabel("")
    ax.set_ylabel("")
    ax.legend(loc="right", title="Generated by")
    fig.tight_layout()
    plt.savefig(f"{save_path}{metric}-{type}.png")

plt.rcParams.update({'font.size': 14})

plot_metric_swarm(
    "comfort",
    [
        "Very\nuncomfortable",
        "Mildly\nuncomfortable",
        "Unsure",
        "Somewhat\ncomfortable",
        "Very\ncomfortable",
    ],
)

plot_metric_swarm(
    "expressivity",
    [
        "Not at all\nexpressive",
        "Mostly not\nexpressive",
        "Unsure",
        "Somewhat\nexpressive",
        "Very\nexpressive",
    ],
)

plot_metric_swarm(
    "idiomatic",
    [
        "Totally\nunidiomatic",
        "Mostly\nunidiomatic",
        "Unsure",
        "Somewhat\nidiomatic",
        "Very\nidiomatic",
    ],
)

plot_metric_swarm(
    "fingering_guess",
    [
        "Definitely\na computer",
        "Probably\na computer",
        "Unsure",
        "Probably\na human",
        "Definitely\na human",
    ],
)
